<?php

namespace Admin\Controller;


use Think\Exception;
use Think\Page;

class ConfigController extends AdminController
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('_nav_show_id', "#setting-nav");
    }


    public function total()
    {
        if (IS_POST) {
            $values = I('id');
            $dbModel = M('system_config');
            foreach ($values as $k => $v) {
                $single['id'] = $k;
                $single['value'] = trim($v);
                $dbModel->save($single);
            }
            $this->success("保存成功！");
        } else {
            $map = array();
            $g = I('get.g');
            if ($g != '') {
                $map['group'] = $g;
            }
            $configs = M('system_config')->where($map)->order("id")->select();
            $this->assign('data_list', $configs);
            $this->display();
        }
    }
}