<?php
/**
 * Mark: 网站开发，软件开发，远程运维
 * Email:zhaojunlike@gmail.com
 * Date: 2016/12/26
 * Time: 19:44
 */

namespace Admin\Controller;


use Think\Page;

class ExpressController extends AdminController
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('_nav_show_id', "#model-nav");
    }

    /*公司*/
    public function company_list($p = 1)
    {
        $map = array();
        $map['del_status'] = 0;
        $count = D('express_company')
            ->where($map)
            ->count();
        $pModel = new Page($count, $this->page_limit);
        $list = D('express_company')
            ->where($map)
            ->page($p, $this->page_limit)
            ->order("id DESC")
            ->select();
        $this->assign('bean_list', $list);
        $this->assign('page', $pModel->show());
        $this->display();
    }

    public function add_company()
    {
        if (IS_POST) {
            $company = M('express_company')->create();
            if (!$company) {
                $this->error(M('express_company')->getError());
            }
            $company['create_time'] = time();
            $addRet = M('express_company')->add($company);
            if ($addRet) {
                $this->success("添加成功");
            } else {
                $this->error("添加失败");
            }
        } else {
            $this->display();
        }
    }

    public function edit_company()
    {
        $map['id'] = I('id');
        $company = M('express_company')->where($map)->find();
        if (IS_POST) {
            $company = M('express_company')->create();
            if (!$company) {
                $this->error(M('express_company')->getError());
            }
            $company['id'] = I('id');
            $addRet = M('express_company')->save($company);
            if ($addRet) {
                $this->success("修改成功");
            } else {
                $this->error("修改失败");
            }
        } else {
            $this->assign('bean', $company);
            $this->display();
        }
    }

    public function del_company($type = 1)
    {
        $ids = I('ids');
        $userIds = array();
        if (!is_array($ids)) {
            $userIds[] = $ids;
        } else {
            $userIds = array_values($ids);
        }
        $userMap['id'] = array('in', $userIds);
        $upRet = false;
        switch ($type) {
            case 1:
                $upRet = M('express_company')->where($userMap)->setField(array('del_status' => 1));
                break;
            case 2:
                $upRet = M('express_company')->where($userMap)->delete();
                break;
        }
        if ($upRet) {
            $this->success("删除成功");
        } else {
            $this->error("删除失败");
        }
    }

}