<?php
/**
 * Mark: 网站开发，软件开发，远程运维
 * Email:zhaojunlike@gmail.com
 * Date: 2016/12/26
 * Time: 19:11
 */

namespace Admin\Controller;


use Think\Page;

class PackageController extends AdminController
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('_nav_show_id', "#package-nav");
    }

    //
    public function index($p = 1)
    {
        $map = array();
        $search = array();

        //
        $yun_no = I('yun_no');
        if ($yun_no != '') {
            $map[] = "`yun_no` like '%{$yun_no}%'";
            $search['yun_no'] = I('yun_no');
        }
        //姓名
        $get_name = I('get_name');
        if ($get_name != '') {
            $map[] = "`get_name` like '%{$get_name}%'";
            $search['get_name'] = I('get_name');
        }
        //手机号
        $get_phone = I('get_phone');
        if ($get_phone != '') {
            $map[] = "`get_phone` like '%{$get_phone}%'";
            $search['get_phone'] = I('get_phone');
        }
        //提货号
        $get_no = I('get_no');
        if ($get_no != '') {
            $map[] = "`get_no` like '%{$get_no}%'";
            $search['get_no'] = I('get_no');
        }
        //门号
        $get_address = I('get_address');
        if ($get_address != '') {
            $map[] = "`get_address` like '%{$get_address}%'";
            $search['get_address'] = I('get_address');
        }
        //状态
        $status = trim(I('status'));
        if ($status != '') {
            $map["p.status"] = $status;
            $search['status'] = I('status');
        }
        //类型
        $package_type_id = intval(I('package_type_id'));
        if ($package_type_id > 0) {
            $map['p.package_type_id'] = $package_type_id;
            $search['package_type_id'] = $package_type_id;
        }
        //快递公司
        $company_id = intval(I('company_id'));
        if ($company_id > 0) {
            $map['p.company_id'] = $company_id;
            $search['company_id'] = $company_id;
        }
        //开始日期
        $start_date = I('start_date');
        if ($start_date != '') {
            $tS = strtotime($start_date);
            $map[] = "push_time >={$tS}";
            $search['start_date'] = $start_date;
        }
        //结束日期
        $end_date = I('end_date');
        if ($end_date != '') {
            $tE = strtotime($end_date);
            $map[] = "push_time <={$tE}";
            $search['end_date'] = $end_date;
        }
        //门店名称
        $home_name = I('home_name');
        if ($home_name != '') {
            $map[] = "u.username like '%{$home_name}%'";
            $search['home_name'] = I('home_name');
        }


        $packages = M('package p')
            ->join('LEFT JOIN ey_user u ON u.id=p.uid')
            ->join('LEFT JOIN ey_system_upload s ON s.id=p.out_img_id')
            ->join('LEFT JOIN ey_express_company c ON c.id=p.company_id')
            ->where($map)
            ->page($p, $this->page_limit)
            ->field('p.*,u.username,s.path as out_img_path,c.name as company_name')
            ->order("p.push_time DESC")
            ->select();

        $count = M('package p')
            ->join('LEFT JOIN ey_user u ON u.id=p.uid')
            ->where($map)
            ->count();

        $pModel = new Page($count, $this->page_limit);
        $this->assign('package_list', $packages);
        $this->assign('page', $pModel->show());
        $this->assign('search', $search);
        $this->display();
    }

    //api json
    public function api_get_package($p = 1)
    {
        $map = array();
        $packages = M('package p')
            ->join('LEFT JOIN ey_user u ON u.id=p.uid')
            ->join('LEFT JOIN ey_system_upload s ON s.id=p.out_img_id')
            ->join('LEFT JOIN ey_express_company c ON c.id=p.company_id')
            ->where($map)
            ->page($p, $this->page_limit)
            ->field('p.*,u.username,s.path as out_img_path,c.name as company_name')
            ->order("p.push_time DESC")
            ->select();

        $count = M('package p')
            ->join('LEFT JOIN ey_user u ON u.id=p.uid')
            ->where($map)
            ->count();
        $pModel = new Page($count, $this->page_limit);
        $this->assign('package_list', $packages);
        $this->assign('page', $pModel->show());
        //back json

        $json['package_list'] = $packages;
        $this->restfulReturn(1, 'success', $json);

    }

    public function edit_package($id)
    {


    }

    public function del_package($id)
    {
        $map['id'] = $id;
        M('package')->where($map)->delete();
        $this->success("删除成功");
    }

    public function set_status_package($id, $status)
    {
        $map['id'] = $id;
        M('package')->where($map)->setField('status', $status);
	if ($status == 5) {
            M('package')->where($map)->setField('pop_time', time());
        }
        $this->success("设置成功");
    }

    //统计
    public function dashboard()
    {

    }

    /*包裹*/
    public function type_list($p = 1)
    {
        $map = array();
        $map['del_status'] = 0;
        $count = D('package_type')
            ->where($map)
            ->count();
        $pModel = new Page($count, $this->page_limit);
        $list = D('package_type')
            ->where($map)
            ->page($p, $this->page_limit)
            ->select();
        $this->assign('bean_list', $list);
        $this->assign('page', $pModel->show());
        $this->assign('_nav_show_id', "#model-nav");
        $this->display();
    }

    public function add_type()
    {
        if (IS_POST) {
            $company = M('package_type')->create();
            if (!$company) {
                $this->error(M('package_type')->getError());
            }
            $company['create_time'] = time();
            $addRet = M('package_type')->add($company);
            if ($addRet) {
                $this->success("添加成功");
            } else {
                $this->error("添加失败");
            }
        } else {
            $this->display();
        }
    }

    public function edit_type()
    {
        $map['id'] = I('id');
        $company = M('package_type')->where($map)->find();
        if (IS_POST) {
            $company = M('package_type')->create();
            if (!$company) {
                $this->error(M('package_type')->getError());
            }
            $company['id'] = I('id');
            $addRet = M('package_type')->save($company);
            if ($addRet) {
                $this->success("修改成功");
            } else {
                $this->error("修改失败");
            }
        } else {
            $this->assign('bean', $company);
            $this->display();
        }
    }

    public function del_type($type = 1)
    {
        $ids = I('ids');
        $userIds = array();
        if (!is_array($ids)) {
            $userIds[] = $ids;
        } else {
            $userIds = array_values($ids);
        }
        $userMap['id'] = array('in', $userIds);
        $upRet = false;
        switch ($type) {
            case 1:
                $upRet = M('package_type')->where($userMap)->setField(array('del_status' => 1));
                break;
            case 2:
                $upRet = M('package_type')->where($userMap)->delete();
                break;
        }
        if ($upRet) {
            $this->success("删除成功");
        } else {
            $this->error("删除失败");
        }
    }
}
