<?php
/**
 * Mark: 网站开发，软件开发，远程运维
 * Email:zhaojunlike@gmail.com
 * Date: 2016/12/28
 * Time: 19:01
 */

namespace Admin\Controller;


use Think\Page;

class SenderController extends AdminController
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('_nav_show_id', "#sender-nav");
    }

    public function index($p = 1)
    {
        $map = array();
        $search = [];
        $phone = trim(I('phone'));

        if ($phone != '') {
            $map[] = "phone like '%{$phone}%'";
            $search['phone'] = $phone;
        }
        $name = I('name');
        if ($name != '') {
            $map[] = "name like '%{$name}%'";
            $search['name'] = $name;
        }
        //开始日期
        $start_date = I('start_date');
        if ($start_date != '') {
            $tS = strtotime($start_date);
            $map[] = "create_time >={$tS}";
            $search['start_date'] = $start_date;
        }
        //结束日期
        $end_date = I('end_date');
        if ($end_date != '') {
            $tE = strtotime($end_date);
            $map[] = "create_time <={$tE}";
            $search['end_date'] = $end_date;
        }
        $senders = M('sender s')
            ->where($map)
            ->page($p, $this->page_limit)
            ->order("create_time DESC")
            ->select();
        //
        $count = M('sender s')
            ->where($map)
            ->count();

        $pModel = new Page($count, $this->page_limit);

        $this->assign('sender_list', $senders);
        $this->assign('search', $search);
        $this->assign('page', $pModel->show());
        $this->display();
    }

    public function add_sender()
    {
        if (IS_POST) {
            $info = [];
            $info['address'] = I("address");
            $info['phone'] = I("phone");
            $info['name'] = I("name");
            $info['address'] = I("address");
            $info['create_time'] = time();
            $info['del_status'] = 1;
            $addRet = M('sender')->add($info);
            if (!$addRet) {
                $this->error('添加失败');
            }
            $this->success('添加成功', U('sender/index'));
        } else {
            $this->display("ea_sender");
        }
    }

    public function edit_sender($id)
    {
        $infoMap['id'] = $id;
        $info = M('sender')
            ->where($infoMap)
            ->find();
        if (!$info) {
            $this->error("对不起，信息不存在");
        }
        if (IS_POST) {
            //开始修改资料
            $info['address'] = I("address");
            $info['phone'] = I("phone");
            $info['name'] = I("name");
            $info['sender_type'] = I('sender_type');
            $saveRet = M('sender')->save($info);
            $this->success('修改资料成功', U('sender/index'));
        } else {
            $this->assign('info', $info);
            $this->display("ea_sender");
        }
    }

    public function del_sender($type = 2)
    {
        $ids = I('ids');
        $userIds = array();
        if (!is_array($ids)) {
            $userIds[] = $ids;
        } else {
            $userIds = array_values($ids);
        }
        $userMap['id'] = array('in', $userIds);
        $upRet = false;
        switch ($type) {
            case 1:
                $upRet = M('sender')->where($userMap)->setField(array('del_status' => 1));
                break;
            case 2:
                $upRet = M('sender')->where($userMap)->delete();
                break;
        }
        if ($upRet) {
            $this->success("删除成功");
        } else {
            $this->error("删除失败");
        }
    }
}