<?php
/**
 * Mark: 网站开发，软件开发，远程运维
 * Email:zhaojunlike@gmail.com
 * Date: 2017/1/7
 * Time: 10:44
 */

namespace Admin\Controller;


use Common\Helper\TreeHelper;
use Common\WeChat\TpWeChat;

class WeMenuController extends AdminController
{
    protected $_wxObj;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('_nav_show_id', "#wechat-nav");
        $this->_wxObj = new TpWeChat(C('WECAHT_OPTIONS'));
    }

    public function menu_list()
    {
        $map = [];
        $menus = M('wechat_menu')->where($map)->select();
        $helper = new TreeHelper();
        $helper->load($menus);
        $menus = $helper->DeepTree();
        $this->assign('data_list', $menus);
        $this->display();
    }

    public function add_menu()
    {

    }

    //同步菜单
    public function sync_menu()
    {
        $map = [];
        $menus = M('wechat_menu')->where($map)->select();
        $helper = new TreeHelper("id", "pid", "sub_button");
        $helper->load($menus);
        $menus = $helper->DeepTree();
        $json['button'] = $menus;
        $ret = $this->_wxObj->createMenu($json);
        if (!$ret) {
            $this->error("同步菜单失败");
        } else {
            $this->success("同步菜单成功");
        }
    }

    public function rm_menu()
    {

    }

    public function edit_menu()
    {

    }
}