<?php
/**
 * Email:zhaojunlike@gmail.com
 * Date: 2017/1/7
 * Time: 15:39
 */

namespace Admin\Controller;


use Think\Page;

class WeUserController extends AdminController
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('_nav_show_id', "#wechat-nav");
    }

    public function index($p = 1)
    {
        $map = array();
        $search = [];
        $phone = trim(I('phone'));

        if ($phone != '') {
            $map[] = "phone like '%{$phone}%'";
            $search['phone'] = $phone;
        }
        $data = M('wechat_user s')
            ->where($map)
            ->page($p, $this->page_limit)
            ->order("create_time DESC")
            ->select();
        //
        $count = M('wechat_user s')
            ->where($map)
            ->count();

        $pModel = new Page($count, $this->page_limit);

        $this->assign('data_list', $data);
        $this->assign('search', $search);
        $this->assign('page', $pModel->show());
        $this->display();
    }
}